//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace manage_2525d_styles {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchema.xsd", IsNullable=false)]
    public partial class ManageStylesConfig {
        
        private string homeField;
        
        private string militaryFeaturesDataHomeField;
        
        private string jMSMLHomeField;
        
        private string graphicHomeField;
        
        private string inkscapeHomeField;
        
        private string cSVtoStyleHomeField;
        
        private string sQLiteHomeField;
        
        private string stylxHomeField;
        
        private string proHomeField;
        
        private string projectHomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string MilitaryFeaturesDataHome {
            get {
                return this.militaryFeaturesDataHomeField;
            }
            set {
                this.militaryFeaturesDataHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string JMSMLHome {
            get {
                return this.jMSMLHomeField;
            }
            set {
                this.jMSMLHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string GraphicHome {
            get {
                return this.graphicHomeField;
            }
            set {
                this.graphicHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string InkscapeHome {
            get {
                return this.inkscapeHomeField;
            }
            set {
                this.inkscapeHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string CSVtoStyleHome {
            get {
                return this.cSVtoStyleHomeField;
            }
            set {
                this.cSVtoStyleHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string SQLiteHome {
            get {
                return this.sQLiteHomeField;
            }
            set {
                this.sQLiteHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string StylxHome {
            get {
                return this.stylxHomeField;
            }
            set {
                this.stylxHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ProHome {
            get {
                return this.proHomeField;
            }
            set {
                this.proHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ProjectHome {
            get {
                return this.projectHomeField;
            }
            set {
                this.projectHomeField = value;
            }
        }
    }
}
