# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# change data source.py
# Created on: 2016-08-29 10:26:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

inputProject = arcpy.mp.ArcGISProject("CURRENT")

inputFeatureDS = arcpy.GetParameterAsText(0)
outputFeatureDS = arcpy.GetParameterAsText(1)

inputProject.updateConnectionProperties(inputFeatureDS, outputFeatureDS)
inputProject.save()
del inputProject